/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package vista;

import controlador.*;
import java.awt.Image;
import java.util.ArrayList;
import java.util.GregorianCalendar;
import javax.swing.Icon;
import javax.swing.ImageIcon;
import javax.swing.JButton;
import javax.swing.JOptionPane;
import modelo.*;

/**
 *
 * @author alumno
 */
public class JVisualizar1a1 extends javax.swing.JPanel {

    /**
     * Creates new form JPanelVer
     */
    public JVisualizar1a1() {
        initComponents();
        ArrayList<String> listaApellidos = new ArrayList<String>();
        
        listaApellidos = ConexionConsulta.llenar_combo();
        
        for(int i=0; i<listaApellidos.size(); i++)
        {
            jComboBox_Apellidos.addItem(listaApellidos.get(i));
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel_Nombre = new javax.swing.JLabel();
        jLabel_Salario = new javax.swing.JLabel();
        jLabel_Fecha = new javax.swing.JLabel();
        jLabel_SueldoMaximo = new javax.swing.JLabel();
        jTextField_Nombre = new javax.swing.JTextField();
        jTextField_Salario = new javax.swing.JTextField();
        jTextField_Fecha = new javax.swing.JTextField();
        jTextField_SueldoMaximo = new javax.swing.JTextField();
        jButton_Siguiente = new javax.swing.JButton();
        jButton_Anterior = new javax.swing.JButton();
        jLabel_Titulo = new javax.swing.JLabel();
        jLabelCodEmpleado = new javax.swing.JLabel();
        jTextFieldCod = new javax.swing.JTextField();
        jButtonFoto = new javax.swing.JButton();
        jLabel_Apellido = new javax.swing.JLabel();
        jTextField_Apellido = new javax.swing.JTextField();
        jComboBox_Apellidos = new javax.swing.JComboBox<>();

        jLabel_Nombre.setText("Nombre:");

        jLabel_Salario.setText("Salario: ");

        jLabel_Fecha.setText("Fecha:");

        jLabel_SueldoMaximo.setText("Sueldo máximo:");

        jTextField_Nombre.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField_NombreActionPerformed(evt);
            }
        });

        jTextField_Salario.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField_SalarioActionPerformed(evt);
            }
        });

        jTextField_SueldoMaximo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField_SueldoMaximoActionPerformed(evt);
            }
        });

        jButton_Siguiente.setText("Siguiente");
        jButton_Siguiente.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton_SiguienteActionPerformed(evt);
            }
        });

        jButton_Anterior.setText("Anterior");
        jButton_Anterior.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton_AnteriorActionPerformed(evt);
            }
        });

        jLabel_Titulo.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel_Titulo.setText("DATOS EMPLEADO");

        jLabelCodEmpleado.setText("Número de empleado: ");

        jTextFieldCod.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextFieldCodActionPerformed(evt);
            }
        });

        jButtonFoto.setIcon(new javax.swing.ImageIcon(getClass().getResource("/fotos/anonimo.png"))); // NOI18N

        jLabel_Apellido.setText("Apellido: ");

        jComboBox_Apellidos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jComboBox_ApellidosActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(27, 27, 27)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jButton_Anterior)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jButton_Siguiente)
                        .addGap(50, 50, 50))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel_Fecha)
                            .addComponent(jLabel_SueldoMaximo)
                            .addComponent(jLabel_Salario)
                            .addComponent(jLabel_Nombre)
                            .addComponent(jLabelCodEmpleado)
                            .addComponent(jLabel_Apellido))
                        .addGap(93, 93, 93)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jTextFieldCod)
                            .addComponent(jTextField_Nombre)
                            .addComponent(jTextField_SueldoMaximo)
                            .addComponent(jTextField_Fecha)
                            .addComponent(jTextField_Salario)
                            .addComponent(jTextField_Apellido))
                        .addContainerGap())))
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jComboBox_Apellidos, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(80, 80, 80)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jButtonFoto, javax.swing.GroupLayout.PREFERRED_SIZE, 215, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel_Titulo))
                .addContainerGap(229, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(33, 33, 33)
                .addComponent(jLabel_Titulo)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jButtonFoto, javax.swing.GroupLayout.PREFERRED_SIZE, 219, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 18, Short.MAX_VALUE)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabelCodEmpleado)
                            .addComponent(jTextFieldCod, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel_Nombre)
                            .addComponent(jTextField_Nombre, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel_Apellido)
                            .addComponent(jTextField_Apellido, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(20, 20, 20)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel_Salario)
                            .addComponent(jTextField_Salario, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel_SueldoMaximo)
                            .addComponent(jTextField_SueldoMaximo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel_Fecha)
                            .addComponent(jTextField_Fecha, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(64, 64, 64)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jButton_Siguiente)
                            .addComponent(jButton_Anterior))
                        .addGap(76, 76, 76))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jComboBox_Apellidos, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void jButton_SiguienteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton_SiguienteActionPerformed
        // TODO add your handling code here:

/*        if (!JFrameMenu.getLista().esUltimo()) { //mientras no hayamos llegado al final de la lista podremos avanzar al siguiente elemento 
            JFrameMenu.getLista().avanzar();
        } else {
            jButton_Siguiente.setEnabled(false); //si estamos al final de la lista inhabilitamos el boton de siguiente
        }

        this.muestraNodo(JFrameMenu.getLista()); //mostramos el nodo en el que estamos actualmente

        jButton_Anterior.setEnabled(true); //como no estamos en el primero el boton anterior lo habilitamos
*/
    }//GEN-LAST:event_jButton_SiguienteActionPerformed

    private void jTextField_SueldoMaximoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField_SueldoMaximoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField_SueldoMaximoActionPerformed

    private void jButton_AnteriorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton_AnteriorActionPerformed
        // TODO add your handling code here:
 /*       if (!JFrameMenu.getLista().esPrimero()) { //mientras no hayamos llegado al principio de la lista podremos retorceder al anterior elemento 
            JFrameMenu.getLista().retroceder();
        } else {
            jButton_Anterior.setEnabled(false); //si estamos al principio de la lista inhabilitamos el boton de anterior
        }

        this.muestraNodo(JFrameMenu.getLista()); //mostramos el nodo en el que estamos actualmente

        jButton_Siguiente.setEnabled(true); //como no estamos en el ultimo el boton siguiente lo habilitamos
*/
    }//GEN-LAST:event_jButton_AnteriorActionPerformed

    private void jTextField_NombreActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField_NombreActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField_NombreActionPerformed

    private void jTextFieldCodActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextFieldCodActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextFieldCodActionPerformed

    private void jTextField_SalarioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField_SalarioActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField_SalarioActionPerformed

    private void jComboBox_ApellidosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jComboBox_ApellidosActionPerformed
        // TODO add your handling code here:        
    }//GEN-LAST:event_jComboBox_ApellidosActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButtonFoto;
    private javax.swing.JButton jButton_Anterior;
    private javax.swing.JButton jButton_Siguiente;
    private javax.swing.JComboBox<String> jComboBox_Apellidos;
    private javax.swing.JLabel jLabelCodEmpleado;
    private javax.swing.JLabel jLabel_Apellido;
    private javax.swing.JLabel jLabel_Fecha;
    private javax.swing.JLabel jLabel_Nombre;
    private javax.swing.JLabel jLabel_Salario;
    private javax.swing.JLabel jLabel_SueldoMaximo;
    private javax.swing.JLabel jLabel_Titulo;
    private javax.swing.JTextField jTextFieldCod;
    private javax.swing.JTextField jTextField_Apellido;
    private javax.swing.JTextField jTextField_Fecha;
    private javax.swing.JTextField jTextField_Nombre;
    private javax.swing.JTextField jTextField_Salario;
    private javax.swing.JTextField jTextField_SueldoMaximo;
    // End of variables declaration//GEN-END:variables

  /*  public void aumentaSueldo(Empleado aux, float nuevoSueldo) throws SueldoSuperadoException {
        aux.setSueldo(nuevoSueldo);
    }
    */
  /*  public void muestraNodo(Lista list) {

        jButton_Siguiente.setEnabled(true); //Ponemos los botones al estado inicial
        jButton_Anterior.setEnabled(true);
        jButtonCalcular.setEnabled(true);

        if (list.esVacia()) { //si la lista esta vacia hay que inicializar los botones
            jButton_Siguiente.setEnabled(false);
            jButton_Anterior.setEnabled(false);
            jButtonCalcular.setEnabled(false);
            jLabelDato1.setText("Dato 1");
            jLabelDato2.setText("Dato 2");
            return;
        }

        if (list.getActual().getDatoObjeto() instanceof Analista) //Comprobación del tipo de cuenta para cambiar los label y mostrar los campos correspondientes
        {
            Analista aux = (Analista) list.getActual().getDatoObjeto(); 
            if (aux.cumpleAño()) {
                jButtonCalcular.setEnabled(true);
            } else {
                jButtonCalcular.setEnabled(false);
            }
            jLabelDato1.setText("Plus Anual");
            jLabelDato2.setText("Departamento");

            if (aux.getNombre() == null || aux.getNombre().equals("")) //Cambiamos el texto del nombre del Empleado al ser transient en caso de ser null
            {
                jTextField_Nombre.setText("**********");
            } else {
                jTextField_Nombre.setText(aux.getNombre());
            }
            jTextFieldCod.setText(String.valueOf(aux.getNumero()));
            jTextField_Salario.setText(String.valueOf(aux.getSueldo()) + " euros");
            jTextField_Fecha.setText(Terminal.stringFecha(aux.getFechaAlta()));
            jTextField_SueldoMaximo.setText(String.valueOf(aux.getSueldo_max()) + " euros");
            jTextField_Dato1.setText(String.valueOf(aux.getDato()) + " %");
            jTextField_Dato2.setText(aux.getDepartamento());

        } else {
            Programador aux = (Programador) list.getActual().getDatoObjeto();
            if (aux.cumpleMes()) {
                jButtonCalcular.setEnabled(true);
            } else {
                jButtonCalcular.setEnabled(false);
            }
            jLabelDato1.setText("Extra Mensual: ");
            jLabelDato2.setText("Proyectos Terminados:");
            if (aux.getNombre() == null || aux.getNombre().equals("")) //Cambiamos el texto del nombre del Empleado al ser transient en caso de ser null
            {
                jTextField_Nombre.setText("**********");
            } else {
                jTextField_Nombre.setText(aux.getNombre());
            }
            jTextFieldCod.setText(String.valueOf(aux.getNumero()));
            jTextField_Salario.setText(String.valueOf(aux.getSueldo()) + " euros");
            jTextField_Fecha.setText(Terminal.stringFecha(aux.getFechaAlta())); 
            jTextField_SueldoMaximo.setText(String.valueOf(aux.getSueldo_max()) + " euros");
            jTextField_Dato1.setText(String.valueOf(aux.getDato()) + " euros");
            jTextField_Dato2.setText(String.valueOf(aux.getProyectosTerminados()));
        }
        //jTextField_Dato2.setEditable(false);

        if (list.esPrimero()) //Comprobacion para desactivar los botones
        {
            jButton_Anterior.setEnabled(false);
        }

        if (list.esUltimo()) {
            jButton_Siguiente.setEnabled(false);
        }

    }

   private void mirarTipoPanel() //Comprobamos cual es la clase hija para cambiar las etiquetas a los datos extra que tienen ambas cada una
    {
        if (JFrameMenu.getLista().getActual().getDatoObjeto() instanceof Analista) //en función de la clase, se pone los Labels unos u otros
        {
            jLabelDato1.setText("Plus Anual: ");
            jLabelDato2.setText("Departamento");
        } else {
            jLabelDato1.setText("Extra Mensual: ");
            jLabelDato2.setText("Proyectos Terminados: ");
        }
    }
*/
    public void muestraNodo() {
            //jButtonFoto.setEnabled(false);
            jTextFieldCod.setText("1002");
            jTextField_Salario.setText(2000 + " euros");
            jTextField_Fecha.setText("12/12/2000");
            jTextField_SueldoMaximo.setText(2500 + " euros");
            jButtonFoto.setIcon(setIcon("/fotos/1002.jpg", jButtonFoto));
    }
    
    public Icon setIcon(String url, JButton boton)
    {
        ImageIcon icon = new ImageIcon(getClass().getResource(url));
        
        int ancho = boton.getWidth();
        int alto = boton.getHeight();
        
        ImageIcon icono = new ImageIcon(icon.getImage().getScaledInstance(ancho, alto, Image.SCALE_DEFAULT));
        
        return icon;
    }
    
    public void vaciarCampos() {
        jTextFieldCod.setText("");
        jTextField_Nombre.setText("");
        jTextField_Salario.setText("");
        jTextField_Fecha.setText("");
        //jTextField_SueldoMaximo.setText(String.valueOf(Empleado.getSueldo_max()));

    }

}
